services:
  config-service:
    container_name: config-service
    build:
      context: .
      dockerfile: ./config-service/Dockerfile
  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: ./discovery-service/Dockerfile
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
  book-service:
    container_name: book-service
    build:
      context: .
      dockerfile: ./book-service-parent/book-service/Dockerfile
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8761/eureka
    depends_on:
      - config-service
      - discovery-service
  book-recommendation-service:
    container_name: book-recommendation-service
    build:
      context: .
      dockerfile: ./book-recommendation-service/Dockerfile
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    depends_on:
      - config-service
      - discovery-service
      - book-service
