spring:
  cloud:
    gateway:
      routes:
        - id: book-recommendation-service
          uri: lb://BOOK-RECOMMENDATION-SERVICE
          predicates:
            - Path=/api/book-recommendation
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}